version: "3.3"
services:
  infosystem:
    build: .
    image: infosystem
    container_name: infosystem
    restart: unless-stopped
    ports:
      - 3003:3000
    environment:
      - TZ=Europe/Madrid
